### ISSUE TITLE
Authentication Service Repositories

### ISSUE THREAD

**Issue by grecosoft** [Boondocks/Boondocks#25]
- Implement the LDAP repository to determine if user is a valid Boondocks user.  Check should happen before the user is authenticated.
- Implement the service/repository that determines the access that can be granted to a device - talk to Rich there is a 2 phase check.

**Comment by rquackenbush** [comment]
Logic for determining if a device has access to a given repository / tag:

If the repository name is `agent`, the agent is attempting to pull an agent version image:
- Get the effective agent version for the device. 
  - If the column `Devices.AgentVersionId` has a value, use this value.  This value always supersedes the value at the application level.
  - Otherwise, each device belongs to one and only one application. Look at the corresponding `Applications.AgentVersionId` value.
  - If neither of these have a value, no access can be granted.
- Take the effective AgentVersionId and get the name from the `AgentVersions.Name` column. 
  - If the requested tag (with the registry information stripped) equals this name, allow `pull`. 
  - Otherwise, unauthorized.

If the repository name is a guid, the agent is attempting to pull an application version image:
- Determine if the device is in the specified application. If it is, continue. Otherwise, unauthorized.
- Get the effective application version for the device.
  - If the column `Devices.ApplicationVersionId` has a value, this is the effective application version.
  - Otherwise, query the `Application.ApplicationVersionId`. If this has a value, this is the effective application version.
  - If no effective application version has been found - unauthorized.
- Take the effective ApplicationVersionId and get the name from the `ApplicationVersions.Name` column.
  - If the requested tag (with the registry information stripped) equals this name, allow `pull`. 
  - Otherwise, unauthorized.
